kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs-static-pvc
spec: 
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: "efs-static-pv"
  resources:
    requests:
      storage: 20Gi