kind: Pod
apiVersion: v1
metadata:
  name: efs-static-pod
  labels:
    purpose: "efs-static-demo"
spec:
  containers:
  - name: nginx
    image: nginx
  volumeMounts:
  - name: persistent-storage
    mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: "efs-static-pvc"

---

kind: Service
apiVersion: v1
metadata: 
  name: efs-static-service
spec:
  type: LoadBalancer
  selector:
    purpose: "efs-static-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
  