kind: Pod
apiVersion: v1
metadata:
  name: ebs-static-pod
  labels: 
    purpose: "ebs-static-demo"
spec: 
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d #
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: ebs-static
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "ebs-static-demo"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007