kind: Pod
apiVersion: v1

metadata: 
  name: annotation
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    project: expense
    environemnt: dev
spec: 
  containers:
  - name: nginx
    image: nginx