kind: Service
apiVersion: v1
metadata:
  name: loadbalancer
  type: LoadBalancer
  selector:
    project: expense
    component: backend
    environment: dev
    version: lb1
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
---

kind: Pod
apiVersion: v1
metadata: 
  name: podlb1
  labels:
    project: expense
    component: backend 
    environment: dev
    version: lb1
spec:
  containers:
  - name: nginx
    image: nginx